#-- Global
language: en-US
name: Jeff Kereakoglow
title: Jeff Kereakoglow
description: Ideas, notes, code
timezone: America/New_York
permalink: /:year/:month/:title/
url: http://jeffkereakoglow.com
branch: master

#-- Styles
highlighter: pygments
markdown: kramdown

ga_tracking_id: UA-56330510-1

defaults:
  - scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

#-- Local configuration
detach:  false
port:    4000
host:    127.0.0.1
