language: en-US
name: Jeff Kereakoglow
title: J. Kereakoglow
description: Ideas, notes, code
timezone: America/New_York
highlighter: pygments
permalink: /:year/:month/:title/
url: http://jeffkereakoglow.com
#-- Local configuration
detach:  false
port:    4000
host:    127.0.0.1
